import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";
import { AppSidebar } from "./_components/app-sidebar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      > 


       <SidebarProvider>
         <AppSidebar/>
           <SidebarTrigger />
           <main>
             {children}
           </main>
        
       </SidebarProvider>
       
        
      </body>
    </html>
  );
}
